# stats available at
# https://travis-ci.org/strukturag/spreed-webrtc/
language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6

env:
  - GEM_HOME=/var/lib/gems/1.9.1 USE_GODEPS=0
  - GEM_HOME=/var/lib/gems/1.9.1 USE_GODEPS=1

before_install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update

install:
  - sudo apt-get -y install nodejs python-babel ruby1.9.1-dev
  - sudo gem1.9.1 install compass
  - sudo gem1.9.1 install scss-lint
  - npm install
  - if [ "$USE_GODEPS" = "1" ]; then wget https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm && chmod +x gpm && sudo mv gpm /usr/local/bin; fi

script:
  - ./autogen.sh
  - ./configure
  - if [ "$USE_GODEPS" = "0" ]; then make get; fi
  - if [ "$USE_GODEPS" = "1" ]; then make gpm; fi
  - make styleshint
  # TODO(fancycode): enable styleslint once all styles have been fixed
  # - make styleslint
  - make styles
  - make jshint
  - make javascript
  - make test
  - make binary
  - make build-i18n
